//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirSupplyPDCEntities : DbContext
    {
        public AirSupplyPDCEntities()
            : base("name=AirSupplyPDCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Area> tb_Area { get; set; }
        public virtual DbSet<tb_Cabinet> tb_Cabinet { get; set; }
        public virtual DbSet<tb_Cell> tb_Cell { get; set; }
        public virtual DbSet<tb_InOutRecord> tb_InOutRecord { get; set; }
        public virtual DbSet<tb_Location> tb_Location { get; set; }
        public virtual DbSet<tb_Merchandise> tb_Merchandise { get; set; }
        public virtual DbSet<tb_Model> tb_Model { get; set; }
        public virtual DbSet<tb_Part> tb_Part { get; set; }
        public virtual DbSet<tb_Remain> tb_Remain { get; set; }
        public virtual DbSet<tb_SettingCabinetCell> tb_SettingCabinetCell { get; set; }
        public virtual DbSet<tb_SettingCabinetPart> tb_SettingCabinetPart { get; set; }
        public virtual DbSet<tb_SettingPart> tb_SettingPart { get; set; }
    
        public virtual ObjectResult<Nullable<System.DateTime>> GetTimeNow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("GetTimeNow");
        }
    }
}
