//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cabinet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Cabinet()
        {
            this.tb_InOutRecord = new HashSet<tb_InOutRecord>();
            this.tb_Remain = new HashSet<tb_Remain>();
            this.tb_SettingCabinetCell = new HashSet<tb_SettingCabinetCell>();
            this.tb_SettingCabinetPart = new HashSet<tb_SettingCabinetPart>();
        }
    
        public int ID_ { get; set; }
        public int ID_LOC { get; set; }
        public string NAME_ { get; set; }
        public int CAPACITY_ { get; set; }
        public bool ISRETURN_ { get; set; }
        public Nullable<int> ID_CELL_MAIN { get; set; }
        public bool ENABLE_ { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual tb_Cell tb_Cell { get; set; }
        public virtual tb_Location tb_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InOutRecord> tb_InOutRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Remain> tb_Remain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SettingCabinetCell> tb_SettingCabinetCell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SettingCabinetPart> tb_SettingCabinetPart { get; set; }
    }
}
