//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Merchandise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Merchandise()
        {
            this.tb_SettingPart = new HashSet<tb_SettingPart>();
        }
    
        public int ID_ { get; set; }
        public string NAME_ { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SettingPart> tb_SettingPart { get; set; }
    }
}
