//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Part
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Part()
        {
            this.tb_InOutRecord = new HashSet<tb_InOutRecord>();
            this.tb_Remain = new HashSet<tb_Remain>();
            this.tb_SettingCabinetPart = new HashSet<tb_SettingCabinetPart>();
            this.tb_SettingPart = new HashSet<tb_SettingPart>();
        }
    
        public string PARTID { get; set; }
        public string NAME_ { get; set; }
        public string VENDOR_ { get; set; }
        public int PCSPBOX_ { get; set; }
        public bool NAMEBACK_ { get; set; }
        public bool ENABLE_ { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public Nullable<int> type_part { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InOutRecord> tb_InOutRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Remain> tb_Remain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SettingCabinetPart> tb_SettingCabinetPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SettingPart> tb_SettingPart { get; set; }
    }
}
