//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Remain
    {
        public int ID_ { get; set; }
        public int ID_AREA { get; set; }
        public int ID_CABINET { get; set; }
        public string PARTID { get; set; }
        public Nullable<System.DateTime> ONCONVEYOR_DATE { get; set; }
        public Nullable<System.DateTime> INSTORE_DATE { get; set; }
        public bool ISFINISH { get; set; }
    
        public virtual tb_Area tb_Area { get; set; }
        public virtual tb_Cabinet tb_Cabinet { get; set; }
        public virtual tb_Part tb_Part { get; set; }
    }
}
