//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SettingCabinetPart
    {
        public int ID_CABINET { get; set; }
        public string PARDID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual tb_Cabinet tb_Cabinet { get; set; }
        public virtual tb_Part tb_Part { get; set; }
    }
}
