//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirSupplyPDC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SettingPart
    {
        public string PARTID { get; set; }
        public int ID_MER { get; set; }
        public int ID_MODEL { get; set; }
        public int ID_AREA { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual tb_Area tb_Area { get; set; }
        public virtual tb_Merchandise tb_Merchandise { get; set; }
        public virtual tb_Model tb_Model { get; set; }
        public virtual tb_Part tb_Part { get; set; }
    }
}
